Feat/curio/user modal
davidrayc/devcraft-ph pull request #11
Opened 2024-03-16 09:19 UTC by Veritaaaas

Completed the user modal

2024-03-16 12:50 UTC, davidrayc reviewed
Is this really a modal or just a page? I don't see any styling that would make it a modal...

2024-03-16 13:00 UTC, evad-e requested changes
Same concern with @davidrayc. No styling for modal.

2024-03-21 15:57 UTC, davidrayc approved these changes
Code looks like it should work although I see a lot of things that can be improved. We will discuss those soon. Approving this for now.

2024-03-21 17:54 UTC, evad-e approved these changes

2024-04-01 12:53 UTC, merged