Feat/dove/create user form
davidrayc/devcraft-ph pull request #21
Opened 2024-03-30 12:49 UTC by dovecancode

- [x] Update create user form UI, this time is based on the figma design
- [x] Add confirm box modal both on cancel and proceed user creation

| Create user form | Cancel modal| Proceed modal |
|---------|----------|----------|
|![image](https://github.com/davidrayc/devcraft-ph/assets/142895411/7ef3568d-f210-4abf-a688-9d786bad1151)|![image](https://github.com/davidrayc/devcraft-ph/assets/142895411/3909de34-a0d4-4258-a5b9-45bb8577e371)|![image](https://github.com/davidrayc/devcraft-ph/assets/142895411/daba22d1-1f35-4028-b30a-5f233996870b)|

- [x] play around with nextjs server action
- [x] validate create user form with zod.dev

# Validation UI
![image](https://github.com/davidrayc/devcraft-ph/assets/142895411/61c09eb9-223f-4a0d-b6a8-697aef876fd5)

2024-03-31 13:14 UTC, davidrayc requested changes

2024-03-31 13:14 UTC, davidrayc commented on next.config.js
> +  experimental: {
not needed for version 14 according to docs

2024-03-31 15:02 UTC, davidrayc approved these changes

2024-04-01 00:43 UTC, evad-e approved these changes

2024-04-01 01:24 UTC, merged