feat: drizzle integration and schemas
davidrayc/devcraft-ph pull request #8
Opened 2024-03-13 15:12 UTC by CedricAngeloSina-on

-Drizzle ORM
-Drizzle Studio

-Defined schemas
--admins
--items
--employees
--managers
--users
--audit_histories (not finished)

2024-03-13 16:02 UTC, CedricAngeloSina-on commented
decided to cancel, needs to code review

2024-03-14 12:40 UTC, davidrayc approved these changes

2024-03-14 12:42 UTC, davidrayc requested changes
Change target branch to `develop` instead of to `main`

2024-03-14 13:22 UTC, CedricAngeloSina-on commented
changed branch target to `develop`

2024-03-14 13:31 UTC, davidrayc approved these changes

2024-03-14 20:11 UTC, evad-e requested changes

2024-03-14 20:11 UTC, evad-e commented on db/drizzle/migrations/0000_skinny_veda.sql
> +CREATE TABLE IF NOT EXISTS "admins" (
Let's follow SQL naming convention:
1.) Table names should be singular
2.) Column names should be singular
3.) Column names should be snake case

This also applies to schema file and variable names.

2024-03-14 20:11 UTC, evad-e commented on db/drizzle/migrations/0000_skinny_veda.sql
> +CREATE TABLE IF NOT EXISTS "admins" (
>0000_skinny_veda.sql
>0001_clean_pete_wisdom.sql
>0002_lethal_tombstone.sql

Not really familiar with migrations in NextJS, but ganito ba yung naming nila? Just curious hahaha

2024-03-15 05:22 UTC, CedricAngeloSina-on commented on db/drizzle/migrations/0000_skinny_veda.sql
> +CREATE TABLE IF NOT EXISTS "admins" (
auto generated file names lang yan ng drizzle magmigrate ng db

2024-03-15 05:25 UTC, CedricAngeloSina-on commented on db/drizzle/migrations/0000_skinny_veda.sql
> +CREATE TABLE IF NOT EXISTS "admins" (
you can delete .sql files and migrate again to create a fresh .sql file
command: pnpm drizzl-kit generate:pg

2024-03-15 12:46 UTC, evad-e commented on db/drizzle/migrations/0000_skinny_veda.sql
> +CREATE TABLE IF NOT EXISTS "admins" (
> auto generated file names lang yan ng drizzle magmigrate ng db

Ohhh ang cool namn hahaha

2024-03-15 12:46 UTC, evad-e commented on db/drizzle/migrations/0000_skinny_veda.sql
> +CREATE TABLE IF NOT EXISTS "admins" (
> you can delete (sql files + meta folder) and migrate again to create a fresh .sql file command: pnpm drizzl-kit generate:pg

Sige, please push your changes para ma approve ko thanks!

2024-03-16 13:05 UTC, evad-e approved these changes

2024-03-16 13:36 UTC, merged